name       : pytest-subtests
version    : 0.5.0
release    : 2
source     :
    - https://pypi.io/packages/source/p/pytest-subtests/pytest-subtests-0.5.0.tar.gz : 5bd1e4bf0eda4c89a6cd42b0ee28e1d2ca0848de3fd67ad8cdd6d559ed00f120
license    : MIT
component  : programming.python
summary    : unittest subTest() support and subtests fixture
description: |
    unittest subTest() support and subtests fixture
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
